# 使用github acitons 构建docker 镜像
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t webui-docker .