# 使用github acitons 构建docker 镜像
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
      push:
        description: 'Push to Huawei'
        required: true
        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: swr.cn-east-3.myhuaweicloud.com
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2 # docker build & push
        with:
          context: .
          push: ${{ github.event.inputs.push }}
          tags: ${{ github.event.inputs.tag }}
          labels: cloud-webui
          cache-from: type=gha
          cache-to: type=gha,mode=max
